from datetime import date

# Change specific banner names
BANNER_NAME_CHANGE = (
    # JP Events
    ("Tales of Chaldean Heavy Industries", "Chaldea Boys Collection 2023 Summoning Part 2", "Chaldea Boys Collection 2023 Summoning Campaign 1"),
    ("GUDAGUDA Yamatai-koku 2020 Rerun", "GUDAGUDA Yamatai-koku 2020 Rerun", "GUDAGUDA Yamatai-koku 2020 Rerun Summoning Campaign"),
    ("GUDAGUDA Yamatai-koku 2020 Rerun", "GUDAGUDA Yamatai-koku 2020 Rerun", "GUDAGUDA Yamatai-koku 2020 Rerun FP Summoning Campaign"),
    ("Avalon le Fae Chapter Release Part 2", "Avalon le Fae Chapter Release Part 2 Summoning Campaign 3", "Avalon le Fae Chapter Release Part 2 Summoning Campaign"),
    ("Slapstick Museum", "Chaldea Boys Collection 2021 Summoning Campaign", "Chaldea Boys Collection 2021 Summoning Campaign 1 & 2"),
    ("Christmas 2019 Re-Run", "Christmas 2019 Re-Run", "Christmas 2019 Re-Run Summoning Campaign"),
    ("GUDAGUDA Yamatai-koku 2020", "GUDAGUDA Yamatai-koku 2020", "GUDAGUDA Yamatai-koku 2020 Summoning Campaign"),
    ("GUDAGUDA Yamatai-koku 2020", "GUDAGUDA Yamatai-koku 2020", "GUDAGUDA Yamatai-koku 2020 FP Summoning Campaign"),
    ("Interlude Campaign 3", "Interlude Campaign 3", "Interlude Campaign 3 Summoning Campaign"),
    ("Shimosa Chapter Release", "Shimosa Chapter Release", "Shimosa Chapter Release Summoning Campaign"),
    ("Agartha Chapter Release", "Agartha Chapter Release", "Agartha Chapter Release Summoning Campaign"),
    ("SE.RA.PH", "Fate/EXTRA CCC×Fate/Grand Order", "Fate/EXTRA CCC×Fate/Grand Order Summoning Campaign"),
    ("Chaldea Boys Collection 2017", "Chaldea Boys Collection 2017", "Chaldea Boys Collection 2017 Summoning Campaign"),
    ("Valentine 2016 Event Re-Run", "Valentine 2017 Summoning Campaign", "Valentine 2017 Summoning Campaign 1"),
    ("Valentine 2016 Event Re-Run", "Valentine 2017 Summoning Campaign", "Valentine 2017 Summoning Campaign 2"),
    ("Valentine 2016 Event Re-Run", "Valentine 2017 Summoning Campaign", "Valentine 2017 Summoning Campaign (Male)"),
    ("Solomon Chapter Release", "Solomon Chapter Release", "Solomon Chapter Release Summoning Campaign"),
    ("Babylonia Chapter Release", "Babylonia Chapter Release", "Babylonia Chapter Release Summoning Campaign"),
    ("FGO 2016 Summer Event", "FGO 2016 Summer Event/Event Details Summer Event 2016 Summoning Campaign", "FGO 2016 Summer Event Summoning Campaign 1"),
    ("FGO 2016 Summer Event", "FGO 2016 Summer Event/Part II Event Details Summer Event 2016 Summoning Campaign Part II", "FGO 2016 Summer Event Summoning Campaign 2"),
    ("FGO Summer Festival 2016 ~1st Anniversary~", "FGO Summer Festival 2016 ~1st Anniversary~", "FGO Summer Festival 2016 ~1st Anniversary~ Order-Based Summoning Campaign"),
    ("Camelot Chapter Release", "Camelot Chapter Release", "Camelot Chapter Release Summoning Campaign"),
    ("Onigashima Event", "Onigashima Event", "Onigashima Event Summoning Campaign"),
    ("Journey to The West", "Journey to The West", "Journey to The West Summoning Campaign"),
    ("Fate/Accel Zero Order Event", "Fate/Accel Zero Order (Pre-Event)", "Fate/Accel Zero Order (Pre-Event) Summoning Campaign"),
    ("Fate/Accel Zero Order Event", "Fate/Accel Zero Order Event", "Fate/Accel Zero Order Event Summoning Campaign"),
    ("E Pluribus Unum Chapter Release", "E Pluribus Unum Chapter Release", "E Pluribus Unum Chapter Release Summoning Campaign"),
    ("Cries of The Vengeful Demon in the Prison Tower", "Cries of The Vengeful Demon in the Prison Tower", "Cries of The Vengeful Demon in the Prison Tower Summoning Campaign"),
    ("Saber Wars Event", "Saber Wars Event", "Saber Wars Event Summoning Campaign"),
    ("London Chapter Release", "London Summoning Campaign", "London Chapter Release Summoning Campaign"),
    ("London Chapter Release", "London Campaign 2", "London Summoning Campaign 2"),
    ("New Year Campaign 2016", "New Year Campaign 2016", "New Year Campaign 2016 Summoning Campaign"),
    ("Da Vinci-chan's Choice 2015", "Da Vinci-chan's Choice 2015", "Da Vinci-chan's Choice 2015 Summoning Campaign"),
    ("Okeanos Chapter Release", "Okeanos Summoning Campaign", "Okeanos Chapter Release Summoning Campaign"),
    # NA Events
    ("Heian-kyo Chapter Release", "Heian-kyo Summoning Campaign 2 Summoning Campaign", "Heian-kyo Summoning Campaign 2"),
    ("Fate/Grand Order Absolute Demonic Front: Babylonia Blu-ray Release Campaign Part II", "Fate/Grand Order Absolute Demonic Front: Babylonia Blu-ray Release Campaign Part II", "Fate/Grand Order Absolute Demonic Front: Babylonia Blu-ray Release Campaign Part II Summoning Campaign"),
    ("Valentine 2018 Event Revival", "Valentine 2018 Event Revival Summoning Campaign", "Valentine 2018 Event Revival Summoning Campaign (Female)"),
    ("Valentine 2018 Event Revival", "Valentine 2018 Event Revival Summoning Campaign", "Valentine 2018 Event Revival Summoning Campaign (Male)"),
    ("New Interludes and Knights of the Round Table Summon Campaign", "New Interludes and Knights of the Round Table Summoning Campaign Knights of the Round Table Summoning Campaign", "New Interludes and Knights of the Round Table Summoning Campaign"),
    ("FGO Festival 2018 ~1st Anniversary~", "FGO Festival 2018 ~1st Anniversary~", "FGO Festival 2018 ~1st Anniversary~ Summoning Campaign"),
    ("Chaldea Boys Collection 2018", "Chaldea Boys Collection 2018", "Chaldea Boys Collection 2018 Summoning Campaign"),
    ("Happy New Year 2018", "Happy New Year 2018", "Happy New Year 2018 Summoning Campaign"),
    ("Christmas 2017 Event", "Christmas 2017 Event", "Christmas 2017 Event Summoning Campaign"),
    ("FGO Thanksgiving Special 2017", "FGO Thanksgiving Special 2017", "FGO Thanksgiving Special 2017 Summoning Campaign"),
    ("Okeanos Chapter Release", "Okeanos Campaign 2", "Okeanos Summoning Campaign 2"),
    ("Okeanos Chapter Release", "Okeanos Chapter Release", "Okeanos Chapter Release Summoning Campaign"),
)

# Change the JP banner dates
CORRECT_DATES_JP = {
    ("MELTY BLOOD: TYPE LUMINA Ushiwakamaru & Edmond Dantès Game Entry Commemorative Campaign", "MELTY BLOOD: TYPE LUMINA Ushiwakamaru & Edmond Dantès Game Entry Commemorative Summoning Campaign") : (None, date(2022, 12, 17)),
    ("Christmas 2019 Re-Run", "Christmas 2019 Re-Run Summoning Campaign") : (None, date(2020, 11, 6)),
    ("Aeaean Spring Breeze", "Chaldea Boys Collection 2020 Summoning Campaign") : (None, date(2020, 3, 20)),
    ("19M Downloads Campaign", "19M Downloads Summoning Campaign") : (None, date(2020, 3, 11)),
    ("Fate/stay night Heaven's Feel II Premiere Commemoration Campaign", "Fate/stay night Heaven's Feel II Premiere Commemoration Summoning Campaign") : (None, date(2019, 1, 25)),
    ("Christmas 2017 Event Re-Run", "Christmas 2017 Event Re-Run Summoning Campaign") : (None, date(2018, 11, 28)),
    ("Interlude Campaign 7", "Interlude Campaign 7 Summoning Campaign") : (None, date(2018, 10, 31)),
    ("14M Downloads Campaign", "14M Downloads Summoning Campaign") : (None, date(2018, 9, 12)),
    ("Servant Summer Festival! 2018", "Servant Summer Festival! 2018 Summoning Campaign 3") : (date(2018, 8, 16), None),
    ("Dead Heat Summer Race! Re-run", "Dead Heat Summer Race! Re-run Daily Special Summoning Campaign") : (date(2018, 7, 6), None),
    ("Dead Heat Summer Race! Re-run", "Dead Heat Summer Race! Re-run Summoning Campaign 2") : (date(2018, 7, 4), None),
    ("GUDAGUDA Meiji Ishin Re-run", "GUDAGUDA Meiji Ishin Re-run Summoning Campaign") : (None, date(2018, 6, 1)),
    ("Chaldea Boys Collection 2018", "Chaldea Boys Collection 2018 Summoning Campaign") : (None, date(2018, 3, 21)),
    ("Kara no Kyoukai Collaboration Event Re-run", "Kara no Kyoukai Collaboration Event Re-run Summoning Campaign") : (None, date(2018, 3, 1)),
    ("Fate/EXTRA Last Encore Anime Broadcast Commemoration Campaign", "Fate/EXTRA Last Encore Anime Broadcast Commemoration Summoning Campaign") : (None, date(2018, 2, 11)),
    ("Da Vinci and The 7 Counterfeit Heroic Spirits Rerun Lite Ver", "Da Vinci and The 7 Counterfeit Heroic Spirits Rerun Lite Ver Summoning Campaign") : (None, date(2018, 1, 24)),
    ("Christmas 2016 Event Re-run", "Christmas 2016 Event Re-run Summoning Campaign") : (None, date(2017, 11, 29)),
    ("Shimosa Chapter Release", "Shimosa Chapter Release Summoning Campaign") : (None, date(2017, 11, 1)),
    ("Fate/stay night Heaven's Feel Premiere Commemoration Campaign", "Fate/stay night Heaven's Feel Premiere Commemoration Summoning Campaign") : (None, date(2017, 10, 22)),
    ("Dead Heat Summer Race!", "Dead Heat Summer Race! Daily Special Summoning Campaign") : (date(2017, 8, 24), None),
    ("Dead Heat Summer Race!", "Dead Heat Summer Race! Summoning Campaign 2") : (date(2017, 8, 16), None),
    ("FGO 2016 Summer Event Re-Run", "FGO 2016 Summer Event Re-Run Summoning Campaign 2") : (date(2017, 7, 20), None),
    ("Rashomon Event Rerun", "Rashomon Event Rerun Summoning Campaign") : (None, date(2017, 6, 14)),
    ("9M Downloads Campaign", "9M Downloads Summoning Campaign") : (None, date(2017, 6, 7)),
    ("SE.RA.PH", "SE.RA.PH Summoning Campaign 2") : (date(2017, 5, 10), None),
    ("SE.RA.PH", "Fate/EXTRA CCC×Fate/Grand Order Summoning Campaign") : (None, date(2017, 5, 3)),
    ("Valentine 2016 Event Re-Run", "Valentine 2017 Summoning Campaign 2") : (date(2017, 2, 11), None),
    ("Moon Goddess Event Re-Run", "Moon Goddess Event Re-Run Summoning Campaign") : (None, date(2017, 1, 30)),
    ("Solomon Chapter Release", "Solomon Chapter Release Summoning Campaign") : (None, date(2016, 12, 31)),
    ("Amakusa Shirō Summoning Campaign", "Amakusa Shirō Summoning Campaign") : (None, date(2016, 12, 7)),
    ("FGO 2016 Summer Event", "FGO 2016 Summer Event Summoning Campaign 2") : (date(2016, 8, 22), None),
    ("Camelot Chapter Release", "Camelot Chapter Release Summoning Campaign") : (None, date(2016, 7, 29)),
    ("E Pluribus Unum Chapter Release", "E Pluribus Unum Chapter Release Summoning Campaign") : (None, date(2016, 4, 13)),
    ("AnimeJapan 2016 Exhibition Commemoration Campaign", "AnimeJapan 2016 Exhibition Commemoration Summoning Campaign") : (date(2016, 3, 23), date(2016, 3, 30)),
    ("New Year Campaign 2016", "New Year Campaign 2016 Summoning Campaign") : (None, date(2016, 1, 7)),
    ("4M Downloads Campaign", "4M Downloads Summoning Campaign") : (None, date(2015, 10, 14)),
}

# Change the NA banner dates
CORRECT_DATES_NA = {
    ("Nahui Mictlān Part 2 Chapter Release", "Nahui Mictlān Part 2 Chapter Release Summoning Campaign") : (None, date(2025, 1, 28)),
    ("GUDAGUDA Yamataikoku 2022 Revival", "GUDAGUDA Yamataikoku 2022 Revival Summoning Campaign 2") : (date(2023, 10, 31), None),
    ("Halloween 2023 Event", "Halloween 2023 Event Summoning Campaign 3") : (date(2023, 10, 19), None),
    ("Halloween Trilogy Event", "Halloween Trilogy Event Summoning Campaign") : (None, date(2023, 10, 12)),
    ("Fate/Samurai Remnant Release Campaign", "Fate/Samurai Remnant Release Summoning Campaign") : (None, date(2023, 10, 8)),
    ("Interlude Campaign 17", "Interlude Campaign 17 Summoning Campaign") : (None, date(2023, 10, 4)),
    ("FGO Summer 2023 Event", "FGO Summer 2023 Event Summoning Campaign 3") : (date(2023, 9, 6), None),
    ("FGO Summer 2023 Event", "FGO Summer 2023 Event Summoning Campaign 4") : (date(2023, 9, 13), None),
    ("Back to School Campaign 2023", "Back to School Campaign 2023 Summoning Campaign") : (None, date(2023, 8, 28)),
    ("Grand Nero Festival 2023", "Grand Nero Festival 2023 Summoning Campaign 2") : (date(2023, 8, 6), None),
    ("Avalon le Fae Conclusion Campaign", "Avalon le Fae Conclusion Summoning Campaign 3") : (date(2023, 7, 24), date(2023, 7, 31)),
    ("Avalon le Fae Conclusion Campaign", "Avalon le Fae Conclusion Summoning Campaign 2") : (date(2023, 7, 17), date(2023, 7, 31)),
    ("Avalon le Fae Conclusion Campaign", "Avalon le Fae Conclusion Summoning Campaign 1") : (date(2023, 7, 12), date(2023, 7, 26)),
    ("FGO Festival 2023 ~6th Anniversary~", "FGO 6th Anniversary Commemorative Summoning Campaign") : (None, date(2023, 7, 2)),
    ("Avalon le Fae Part 2 Chapter Release", "Avalon le Fae Part 2 Chapter Release Summoning Campaign") : (None, date(2023, 7, 2)),
    ("Interlude Campaign 16", "Interlude Campaign 16 Summoning Campaign") : (None, date(2023, 6, 29)),
    ("Avalon le Fae Part 1 Chapter Release", "Avalon le Fae Part 1 Chapter Release Summoning Campaign") : (None, date(2023, 6, 19)),
    ("Avalon le Fae Part 1 Chapter Release", "Avalon le Fae Pre-Release Summoning Campaign") : (None, date(2023, 6, 15)),
    ("FGO Summer 2022 Event Revival", "FGO Summer 2022 Event Revival Summoning Campaign 3") : (date(2023, 5, 22), None),
    ("Grail Front Event ~My Super Camelot 2023~", "My Super Camelot 2023 Pre-Release Summoning Campaign") : (None, date(2023, 5, 8)),
    ("FGO Waltz in the Moonlight Collaboration Event", "FGO Waltz in the Moonlight Collaboration Event Summoning Campaign 2") : (date(2023, 4, 20), date(2023, 5, 5)),
    ("White Day 2023 Event", "Chaldea Boys Collection 2023 Summoning Campaign 1") : (None, date(2023, 3, 16)),
    ("Spring has Sprung Campaign 2023", "Spring has Sprung Campaign 2023 Summoning Campaign") : (None, date(2023, 3, 9)),
    ("Saber Wars II Revival", "Saber Wars II Revival Summoning Campaign 2") : (date(2023, 1, 11), date(2023, 1, 25)),
    ("Happy New Year 2023", "Happy New Year 2023 Summoning Campaign 2") : (date(2023, 1, 2), date(2023, 1, 9)),
    ("Christmas 2022 Event", "Christmas 2022 Event Summoning Campaign 2") : (date(2022, 12, 18), date(2022, 12, 26)),
    ("19M Downloads Campaign", "19M Downloads Summoning Campaign") : (None, date(2022, 12, 19)),
    ("Interlude Campaign 15", "Interlude Campaign 15 Summoning Campaign") : (None, date(2022, 12, 11)),
    ("Heian-kyo Chapter Release", "Heian-kyo Chapter Release Summoning Campaign") : (None, date(2022, 12, 4)),
    ("Heian-kyo Chapter Release", "Heian-kyo Pre-Release Summoning Campaign") : (None, date(2022, 11, 20)),
    ("Imaginary Scramble", "Imaginary Scramble Summoning Campaign 2") : (date(2022, 11, 3), date(2022, 11, 13)),
    ("Imaginary Scramble", "Imaginary Scramble Pre-Release Summoning Campaign") : (None, date(2022, 11, 7)),
    ("Christmas 2021 Event Revival", "Christmas 2021 Event Revival Summoning Campaign") : (None, date(2022, 10, 19)),
    ("FGO THE STAGE Solomon Release Campaign", "FGO THE STAGE Solomon Release Summoning Campaign") : (None, date(2022, 10, 5)),
    ("Interlude Campaign 14", "Interlude Campaign 14 Summoning Campaign") : (None, date(2022, 8, 30)),
    ("18M Downloads Campaign", "18M Downloads Summoning Campaign") : (None, date(2022, 8, 23)),
    ("FGO Summer 2022 Event", "FGO Summer 2022 Event Summoning Campaign 4") : (date(2022, 7, 25), date(2022, 8, 6)),
    ("FGO Summer 2022 Event", "FGO Summer 2022 Event Summoning Campaign 3") : (date(2022, 7, 18), None),
    ("FGO Festival 2022 ~5th Anniversary~", "FGO 5th Anniversary Pre-Anniversary Summoning Campaign") : (None, date(2022, 6, 23)),
    ("SE.RA.PH Main Interlude Release Campaign", "SE.RA.PH Main Interlude Release Summoning Campaign") : (None, date(2022, 7, 4)),
    ("FGO Summer 2021 Event Revival", "FGO Summer 2021 Event Revival Summoning Campaign 3") : (date(2022, 5, 29), None),
    ("FGO Summer 2021 Event Revival", "FGO Summer 2021 Event Revival Summoning Campaign 2") : (date(2022, 5, 29), None),
    ("GUDAGUDA Final Honnoji 2021 Revival", "GUDAGUDA Final Honnoji 2021 Revival Summoning Campaign 2") : (date(2022, 4, 24), date(2022, 5, 4)),
    ("17M Downloads Campaign", "17M Downloads Summoning Campaign") : (date(2022, 4, 10), date(2022, 4, 27)),
    ("Olympus Chapter Release", "Olympus Chapter Release Summoning Campaign") : (None, date(2022, 4, 6)),
    ("White Day 2022 Event", "Chaldea Boys Collection 2022 Summoning Campaign") : (None, date(2022, 3, 13)),
    ("16M Downloads Campaign", "16M Downloads Summoning Campaign") : (None, date(2022, 2, 27)),
    ("Interlude Campaign 12", "Interlude Campaign 12 Summoning Campaign") : (None, date(2022, 2, 9)),
    ("New Year 2021 Event Revival", "New Year 2021 Event Revival Summoning Campaign 2") : (date(2022, 1, 10), date(2022, 1, 24)),
    ("Happy New Year 2022", "Happy New Year 2022 Summoning Campaign") : (None, date(2022, 1, 15)),
    ("Christmas 2021 Event", "Christmas 2021 Event Summoning Campaign") : (None, date(2021, 12, 31)),
    ("Atlantis Chapter Release", "Atlantis Chapter Release Summoning Campaign") : (None, date(2021, 12, 14)),
    ("FGO Thanksgiving Special 2021", "FGO Thanksgiving Special 2021 Summoning Campaign") : (None, date(2021, 12, 1)),
    ("Interlude Campaign 11", "Interlude Campaign 11 Summoning Campaign") : (None, date(2021, 11, 29)),
    ("Early Winter Campaign 2021", "Early Winter Campaign 2021 Summoning Campaign") : (None, date(2021, 11, 22)),
    ("15M Downloads Campaign", "15M Downloads Summoning Campaign") : (None, date(2021, 11, 8)),
    ("Saber Wars II", "Saber Wars II Summoning Campaign 2") : (date(2021, 10, 23), date(2021, 11, 6)),
    ("Saber Wars II", "Saber Wars II Pre-Release Summoning Campaign") : (None, date(2021, 10, 31)),
    ("FGO THE STAGE Camelot Release Campaign", "FGO THE STAGE Camelot Release Summoning Campaign 2") : (date(2021, 9, 24), date(2021, 10, 3)),
    ("FGO THE STAGE Camelot Release Campaign", "FGO THE STAGE Camelot Release Summoning Campaign 1") : (None, date(2021, 9, 24)),
    ("FGO Summer 2021 Event", "FGO Summer 2021 Event Summoning Campaign 3") : (date(2021, 8, 4), None),
    ("FGO Summer 2021 Event", "FGO Summer 2021 Event Summoning Campaign 2") : (date(2021, 8, 1), date(2021, 8, 15)),
    ("FGO Summer 2020 Event Revival", "FGO Summer 2020 Event Revival Summoning Campaign 3") : (date(2021, 7, 18), None),
    ("FGO Festival 2021 ~4th Anniversary~", "FGO Festival 2021 ~4th Anniversary~ Summoning Campaign") : (None, date(2021, 7, 17)),
    ("14M Downloads Campaign", "14M Downloads Summoning Campaign") : (None, date(2021, 6, 30)),
    ("Yugakshetra Chapter Release", "Yugakshetra Chapter Release Summoning Campaign") : (None, date(2021, 6, 16)),
    ("Interlude Campaign 9", "Interlude Campaign 9 Summoning Campaign") : (None, date(2021, 6, 10)),
    ("Fate/Grand Order Absolute Demonic Front: Babylonia Blu-ray Release Campaign", "Fate/Grand Order Absolute Demonic Front: Babylonia Blu-ray Release Summoning Campaign") : (None, date(2021, 4, 12)),
    ("Tokugawa Restoration Labyrinth", "Tokugawa Restoration Labyrinth Summoning Campaign 2") : (date(2021, 3, 28), date(2021, 4, 11)),
    ("White Day 2021 Event", "Chaldea Boys Collection 2021 Summoning Campaign") : (None, date(2021, 3, 21)),
    ("Fate/Extra CCC Collaboration Event Revival", "Fate/Extra CCC Collaboration Event Revival Summoning Campaign 2") : (date(2021, 2, 22), date(2021, 3, 8)),
    ("Even More Learning With Manga Release Celebration Campaign", "Even More Learning With Manga Release Celebration Summoning Campaign") : (None, date(2021, 1, 27)),
    ("New Year 2021 Event", "New Year 2021 Event Summoning Campaign 2") : (date(2021, 1, 7), date(2021, 1, 21)),
    ("Happy New Year 2021", "Happy New Year 2021 Summoning Campaign") : (None, date(2021, 1, 15)),
    ("SIN Chapter Release", "SIN Chapter Release Summoning Campaign") : (None, date(2020, 12, 9)),
    ("Fate/Stay Night Heaven's Feel III Theatrical Release Commemorative Campaign", "Fate/Stay Night Heaven's Feel III Theatrical Release Commemorative Summoning Campaign") : (None, date(2020, 11, 25)),
    ("Christmas 2019 Event Revival", "Christmas 2019 Event Revival Summoning Campaign") : (None, date(2020, 11, 25)),
    ("Interlude Campaign 7", "Interlude Campaign 7 Summoning Campaign") : (None, date(2020, 11, 15)),
    ("FGO Summer 2020 Event", "FGO Summer 2020 Event Summoning Campaign 3") : (date(2020, 8, 9), None),
    ("FGO Summer 2019 Event Revival", "FGO Summer 2019 Event Revival Summoning Campaign 3") : (date(2020, 7, 24), None),
    ("FGO Summer 2019 Event Revival", "FGO Summer 2019 Event Revival Summoning Campaign 2") : (date(2020, 7, 23), None),
    ("FGO Festival 2020 ~3rd Anniversary~", "FGO Festival 2020 ~3rd Anniversary~ Summoning Campaign") : (None, date(2020, 7, 20)),
    ("Götterdämmerung Chapter Release", "Götterdämmerung Chapter Release Summoning Campaign") : (None, date(2020, 7, 6)),
    ("GUDAGUDA Meiji Restoration Revival", "GUDAGUDA Meiji Restoration Revival Summoning Campaign") : (None, date(2020, 5, 21)),
    ("Fate/Apocrypha Collaboration Event", "Fate/Apocrypha Event Pre-Release Summoning Campaign") : (None, date(2020, 5, 4)),
    ("Anastasia Chapter Release", "Anastasia Chapter Release Summoning Campaign") : (None, date(2020, 4, 9)),
    ("Chaldea Boys Collection 2020", "Chaldea Boys Collection 2020 Summoning Campaign") : (None, date(2020, 3, 19)),
    ("The Garden of Sinners Collaboration Event Revival", "The Garden of Sinners Collaboration Event Revival Summoning Campaign") : (None, date(2020, 3, 2)),
    ("The Tale of Setsubun", "The Tale of Setsubun Summoning Campaign") : (None, date(2020, 2, 9)),
    ("Da Vinci and the 7 Counterfeit Heroic Spirits Revival", "Da Vinci and the 7 Counterfeit Heroic Spirits Revival Summoning Campaign") : (None, date(2020, 1, 23)),
    ("Happy New Year 2020", "Happy New Year 2020 Summoning Campaign") : (None, date(2020, 1, 19)),
    ("Salem Chapter Release", "Salem Chapter Release Summoning Campaign") : (None, date(2019, 12, 15)),
    ("FGO Thanksgiving Special 2019", "FGO Thanksgiving Special 2019 Summoning Campaign") : (None, date(2019, 12, 2)),
    ("Christmas 2018 Event Revival", "Christmas 2018 Event Revival Summoning Campaign") : (None, date(2019, 11, 26)),
    ("8M Downloads Campaign", "8M Downloads Summoning Campaign") : (None, date(2019, 11, 21)),
    ("Shimousa Chapter Release", "Shimousa Chapter Release Summoning Campaign") : (None, date(2019, 10, 28)),
    ("FGO Summer 2019 Event", "FGO Summer 2019 Event Summoning Campaign 3") : (date(2019, 8, 12), None),
    ("FGO Summer 2019 Event", "FGO Summer 2019 Event Summoning Campaign 2") : (date(2019, 8, 5), None),
    ("FGO Summer 2018 Event Revival", "FGO Summer 2018 Event Revival Summoning Campaign 2") : (date(2019, 7, 19), None),
    ("FGO Festival 2019 ~2nd Anniversary~", "FGO Festival 2019 ~2nd Anniversary~ Summoning Campaign") : (date(2019, 7, 6), date(2019, 7, 23)),
    ("Agartha Chapter Release", "Agartha Chapter Release Summoning Campaign") : (None, date(2019, 7, 6)),
    ("Rashomon Event Revival", "Rashomon Event Revival Summoning Campaign") : (None, date(2019, 6, 6)),
    ("Fate/Extra CCC Collaboration Event", "Fate/Extra CCC Collaboration Event Summoning Campaign 2") : (date(2019, 5, 1), None),
    ("Fate/Extra CCC Collaboration Event", "Fate/Extra CCC Event Pre-Release Summoning Campaign") : (None, date(2019, 4, 22)),
    ("Shinjuku Chapter Release", "Shinjuku Chapter Release Summoning Campaign") : (None, date(2019, 3, 11)),
    ("5M Downloads Campaign", "5M Downloads Summoning Campaign") : (None, date(2019, 2, 6)),
    ("Moon Goddess Event Revival", "Moon Goddess Event Revival Summoning Campaign") : (None, date(2019, 1, 30)),
    ("Solomon Chapter Release", "Solomon Chapter Release Summoning Campaign") : (None, date(2018, 12, 31)),
    ("Babylonia Chapter Release", "Babylonia Chapter Release Summoning Campaign") : (None, date(2018, 12, 31)),
    ("Christmas 2018 Event", "Christmas 2018 Event Summoning Campaign 2") : (date(2018, 12, 2), date(2018, 12, 12)),
    ("FGO Summer 2018 Event", "FGO Summer 2018 Event Summoning Campaign 2") : (date(2018, 8, 6), date(2018, 8, 22)),
    ("FGO Festival 2018 ~1st Anniversary~", "FGO Festival 2018 ~1st Anniversary~ Summoning Campaign") : (None, date(2018, 7, 17)),
    ("Camelot Chapter Release", "Camelot Chapter Release Summoning Campaign") : (None, date(2018, 7, 6)),
    ("E Pluribus Unum Chapter Release", "E Pluribus Unum Chapter Release Summoning Campaign") : (None, date(2018, 3, 29)),
    ("London Chapter Release", "London Chapter Release Summoning Campaign") : (None, date(2018, 1, 4)),
    ("Okeanos Chapter Release", "Okeanos Chapter Release Summoning Campaign") : (None, date(2017, 10, 12)),
    ("Moon Goddess Event", "Moon Goddess Event Summoning Campaign") : (None, date(2017, 8, 31)),
}
